[target.aarch64-linux-ohos]
  compile-option = "--debug-macro -B\"${DEVECO_CANGJIE_HOME}/compiler/third_party/llvm/bin\" -B\"${DEVECO_CANGJIE_HOME}/musl/usr/lib/aarch64-linux-ohos\" -L\"${DEVECO_CANGJIE_HOME}/musl/usr/lib/aarch64-linux-ohos\" -L\"${DEVECO_CANGJIE_HOME}/build/linux_ohos_aarch64_llvm/openssl\" --sysroot \"${DEVECO_CANGJIE_HOME}/musl\""

[dependencies]
  cj_res = {path = "../../../cj_res", version = "1.0.0"}

[ffi.c]
  glwrapper.path = "../../../library"

[package]
  cjc-version = "0.48.2"
  compile-option = ""
  description = "CangjieUI Application"
  link-option = ""
  name = "ohos_app"
  output-type = "dynamic"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
  scripts = {}

[target.aarch64-linux-ohos.bin-dependencies]
  path-option = ["${DEVECO_CANGJIE_HOME}/build/linux_ohos_aarch64_llvm/ohos", "${DEVECO_CANGJIE_HOME}/build/x86_64-w64-mingw32/macro/ohos"]
  package-option = {}

[profile]
  build = {incremental = false, lto = ""}
  customized-option = {debug = "-g -Woff all", release = "--fast-math -O2 -Woff all"}
  test = {}
